// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "API de Citas Médicas",
    "version": "1"
  },
  "paths": {
    "/appointment": {
      "post": {
        "summary": "appointment",
        "description": "",
        "operationId": "appointment.post.appointment",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/appointments/{countryISO}": {
      "get": {
        "summary": "getAppointments",
        "description": "",
        "operationId": "getAppointments.get.appointments/{countryISO}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "countryISO",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swagger": {
      "get": {
        "summary": "swaggerUI",
        "description": "",
        "operationId": "swaggerUI.get.swagger",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swagger.json": {
      "get": {
        "summary": "swaggerUI",
        "description": "",
        "operationId": "swaggerUI.get.swagger.json",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {},
  "basePath": "/",
  "schemes": [
    "https"
  ]
};